name: expenses-tracker
services:
  backend:
    build: ./
    container_name: expenses-tracker-BE
    ports:
      - "9000:3000"
    volumes:
      - ./:/app
      - /app/node_modules

  frontend:
    build: ../ExpensesTrackerFE
    container_name: expenses-tracker-FE
    ports:
      - "8000:5173"
    volumes:
      - ../ExpensesTrackerFE:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE_URL=http://localhost:9000/
      - NODE_ENV=development