paths:
  /getAllExpenses:
    get:
      tags:
        - Expenses
      responses:
        "200":
          description: Successfully retrieved expenses.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      description: Unique identifier for the expense.
                    name:
                      type: string
                      description: Name or description of the expense.
                    amount:
                      type: number
                      description: Expense amount.
        "500":
          description: Internal server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message explaining the failure.

  /getAllExpenses/me:
    get:
      tags:
        - Expenses
      responses:
        "200":
          description: Successfully retrieved expenses.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      description: Unique identifier for the expense.
                    name:
                      type: string
                      description: Name or description of the expense.
                    amount:
                      type: number
                      description: Expense amount.
        "500":
          description: Internal server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message explaining the failure.

  /createExpenses:
    post:
      tags:
        - Expenses
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - title
                - amount
              properties:
                title:
                  type: string
                  description: Title or description of the expense.
                  example: water bill
                amount:
                  type: number
                  description: Amount of the expense.
                  example: 200
      responses:
        "200":
          description: Expense created successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Success message.
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                        description: Unique identifier of the created expense.
                      user_id:
                        type: string
                        description: User ID associated with the expense.
                      title:
                        type: string
                        description: Title or description of the expense.
                      amount:
                        type: number
                        description: Amount of the expense.
                      createdAt:
                        type: string
                        format: date-time
                        description: Timestamp when the expense was created.
                      updatedAt:
                        type: string
                        format: date-time
                        description: Timestamp when the expense was last updated.
        "500":
          description: Internal server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message explaining the failure.
  
  /deleteAllExpenses:
    delete:
      tags:
        - Expenses
      responses:
        "200":
          description: All expenses deleted successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "500":
          description: Server error

  /seederExpenses/me:
    post:
      tags:
        - Expenses
      security:
        - BearerAuth: []
      requestBody:
        description: The user ID for which the expenses are being created.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: string
                  description: The ID of the user for whom the expenses are being created.
                  example: ""
      responses:
        '200':
          description: Expenses created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'Expenses created successfully!'
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        user_id:
                          type: string
                          description: The user ID of the created expense record.
                        title:
                          type: string
                          description: The title/description of the expense.
                        amount:
                          type: number
                          format: float
                          description: The amount of the expense.
                        _id:
                          type: string
                          description: The unique ID of the expense record.
        '400':
          description: Bad request (invalid or missing user_id)
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: 'User ID is required.'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: 'Internal server error.'